apiVersion: v1
kind: Secret
metadata:
  name: aws-secret-udacity
  namespace: default
type: Opaque
data:
  AWS_REGION: dXMtZWFzdC0x
  AWS_DEFAULT_REGION: dXMtZWFzdC0x
  AWS_PROFILE: ZGVmYXVsdA==
  config: |
    W2RlZmF1bHRdCnJlZ2lvbiA9IHVzLWVhc3QtMQpvdXRwdXQgPSBqc29u
  credentials: |
    W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQVNJQVhaM1VLRkQyT0xKRkNOTjcKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gR1BUL2lqcU9oYm1FdkpCS3lQeGw5b29Xa2ljR3BiRkRHWENiY01sdAphd3Nfc2Vzc2lvbl90b2tlbiA9IEZ3b0daWEl2WVhkekVDa2FETFU1TnF1eStXMlkyZEZHWVNMVkFkb3NDN1cxRVZnOGphaEN0K1lxRnoxUzdYNUZ1QlZDTFd4WjIzMnE4aG4xMWFZem45SkRPMDBSMjFBd25USXdZeURIMVlXVmpqU3lLZ2dWbEUyZkJPWkVOYVpIU2VUSkVzdjFXMVRydlpsbE5iT0FpUVVxbGFPUmZqSlBLc1FQS0Y2VHJsT3R5S3I2cDBTTVloVDY1RFJlV3E2OWU3QkRaMVlQcWdMZlMzT1VrZFpPS2N6UU94MGhUajVCdlNGZzdwcmJ4cDFzbHVQZlZNMG1iQjFxQVlLMjUydEs5aVhEWHRudFFhZkNXR2U4aEppRWNDd1lVSWpyUzdhVC9wMWNnWnZtaXBWS0JvcXM1ckg3MFE0bHEwTjVSVmtFOUNpdGdiV29Cakl0eitITmVMakZRNXdOQ25qSDRWNmhYNXNtVnJrWXl4LzBCNngzbTVOY3oxUkVDcGZuc0VTR3BSa1M2V2VS