apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-service-udacity
spec:
  selector:
    app: reverseproxy-deployment-udacity
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080